// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlProblem;
using NpgsqlTypes;

#nullable disable

namespace NpgsqlProblem.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NpgsqlProblem.DummyDataClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Field1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FieldBool")
                        .HasColumnType("boolean");

                    b.Property<int>("FieldInt")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "turkish")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Field1", "Field2", "Field3" });

                    b.HasKey("Id");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("DummyDataClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
